name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs: # press ctrl + space to show available directives
      run_job:
        type: boolean
        description: Run Specific Job
        required: false
      custom_message:
        type: string
        description: Enter a custom message
        required: true
      

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Exploring Workflow Dispatch Trigger"
  job2:
    runs-on: ubuntu-latest
    steps:
    - name: Printing Custom Message
      run: |
        echo ${{ inputs.custom_message }}