name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs: # press ctrl + space to show available directives
      run_job:
        description: Run Specific Job
        required: false  # it is not required to be configured while run
        type: boolean
      custom_message:
        type: string
        description: Enter a custom message
        required: true
      

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Exploring Workflow Dispatch Trigger"
  job2:
    runs-on: ubuntu-latest
    steps:
    - name: Printing Custom Message
      run: |
        echo ${{ inputs.custom_message }}
    - name: Printing run-job boolean value
      if: ${{ inputs.run_job == true }}
      run: |
        echo ${{ inputs.run_job }}